### ISSUE TITLE
Progressive Web Apps e IndexDb

### ISSUE THREAD

**Issue by TiagoGouvea** [gdgjf/gdgjf.github.io#2]
## Descrição 
Apresentação sobre a utilização de PWA e utilização do IndexDb para cache de dados offline.

### Palestrante(s)
- Washington Gilhardes

### Outras considerações iniciais 
O Lesley podia pensar em algo para ementar em um evento seguinte.

**Comment by junior201110** [comment]
Opa to dentro sim.

**Comment by lesleyandrez** [comment]
Evento realizado
