### ISSUE TITLE
Newsletter - changelog

### ISSUE THREAD

**Issue by TiagoGouvea** [gdgjf/gdgjf.github.io#32]
Ao final de cada evento será enviado um email para todos de nossa base informando o que foi apresentado, o que foi dito, com alguns links e informações úteis.

O ideal é que isso pode ser feito de forma fácil, sem necessidade de ferramental muito complexo durante o uso. Que alguém possa tomar as notas do evento e rapidamente "despachar" a informação para todos inscritos.

O projeto é talvez encontrar uma forma boa de fazer acontecer, propor ferramentas, criar um template padrão e sistematizar este processo.

**Comment by fnnrodrigo** [comment]
Tenho interesse em auxiliar nesse projeto!

**Comment by TiagoGouvea** [comment]
@fnnrodrigo quais ferramentas você acha que podem ser usadas?
Temos um mail chimp atualmente.. teria alguma ferramenta mais simples e objetiva pra isso?

**Comment by fnnrodrigo** [comment]
Podemos manter o Mailchimp, Tiago!
Dei uma olhada nas ferramentas que eu conheço e, até 2 mil inscritos o Mailchimp é gratuito e nos atende bem.

Bom, segue as ideias para os changelogs.

A princípio eu havia pensado em transformar isso em uma newsletter semanal ou até quinzenal. Mas, percebi que criaria uma demanda de trabalho recorrente que, no longo prazo, não seria trivial manter a consistência. Por isso, optei por desenhar uma estrutura mais simples, reativa às atividades que forem executadas.

Por isso, mandaremos um Changelog para a comunidade sempre que:

1. Acontecer algum evento (presencial ou online);
2. Organizers tiverem reunião (com definições relevantes para membros);
3. Google lançar algo interessante para comunidade;
4. Grande movimento no mercado que deva ser observado.

Explicarei, com exemplos, cada um dos pontos.

----------------------------

**1) Este ponto é o mais importante dos 4 pois ele conecta o membro da comunidade ao que está acontecendo. A partir dessa mensagem ele poderá se motivar a participar do próximo evento ou abordar quem participou do último, para iniciar uma conversa sobre o assunto.**

Exemplo:

**Typescript, vale a pena? - GDGJF Changelog v1.1**

No último fim de semana o GDGJF organizou um evento de dois dias de imersão com conteúdo e prática sobre Typescript. Neste evento, foram abordados assuntos como:

- Qual usar e quando não usar o Typescript;
- Como implantar em pequenos times e grandes equipes;
- Como lidar com códigos e bibliotecas legadas durante a implementação;
- Aplicação do zero ao Hello World.

O conteúdo do evento já está disponível em nosso site (ou GitHub?) e pode ser consultado aqui: __LINK__. Qualquer dúvida ou novas discussões, chame a gente no Slack ou no grupo do WhatsApp!

Lembrando que, dia xx/xx, abriremos nossa mentoria e você tem apenas mais essa semana para se inscrever. Basta entrar em __LINK__.

----------------------------

**2) Nesse caso, o objetivo é manter. Comunidade informada do que está sendo feito. Manter transparência, aproximar e humanizar a marca GDGJF.**

Exemplo:

**Quer aprender GitHub enquanto ajuda o GDG? - GDGJF Changelog v1.2**

Hoje os organizadores do GDGJF traçaram os próximos passos da nossa comunidade. Além de muita novidade interessante para você, participante, iremos também evoluir nosso site!

Chegou a hora de construir mais funcionalidades e deixá-lo mais útil para você.

Mas, claro, uma comunidade é feita por pessoas e aprendizados, correto? Por isso planejamos um novo modelo. Nosso organizador __NOME__ irá liderar essa nova mudança e você poderá ajudá-lo! 

É sua oportunidade de aprender e utilizar o git e o GitHub com um projeto real, aplicar conhecimentos de HTML, CSS, JS e também contribuir com um projeto opensource pela primeira vez.

Se tiver interesse, basta enviar um email para __EMAIL__  que te passaremos mais detalhes!

----------------------------

**3) A ideia é criar autoridade para a marca GDGJF trazendo informações relevantes e úteis para o participante.**

Exemplo:

**Google I/O lançou novo Android. O que mudou? - GDGJF Changelog v1.3**

Como você já sabe, está rolando o Google I/O e, como esperado, muitas mudanças no Android.

O que mais se destacou no evento foram as seguintes mudanças:
- Mudança 1;
- Mudança 2;
- Mudança 3.

Como acha que isso vai impactar o dia-a-dia de desenvolvimento para essa plataforma? Tá rolando uma discussão bem interessante no nosso Slack. Dá um pulo lá e deixe sua visão: __LINK__

----------------------------

**4) O objetivo desse tópico é o mesmo que o (3), porém, de forma mais abrangente.**

Exemplo:

**Amazon Honeycode, o que impacta para nós, programadores? - GDGJF Changelog v1.4**

Nocode ou lowcode são práticas que já existem há décadas mas, atualmente, estão ganhando um novo destaque. Essa semana a Amazon entrou nesse jogo com o AWS Honeycode. Com ele você consegue criar aplicações desktop e mobile com facilidade, sem utilizar código. Em pouco tempo, tudo fica pronto e você já pode publicar para os usuários.

Você já utilizou alguma ferramenta nocode antes? O que acha do impacto disso para nossa profissão?

Se você gostaria de um evento sobre esse assunto, deixe o seu voto aqui: __LINK__.
E, para saber mais sobre o Honeycode, basta entrar aqui: __LINK__


----------------------------

Bom, quero saber a opinião de vocês sobre esse formato e sobre os exemplos e casos de uso que eu trouxe. Com isso poderemos criar um processo ou um fluxograma que define se algo deverá ou não ser enviado pros membros, qual frequência mínima e máxima, etc.

Fico no aguardo!

**Comment by TiagoGouvea** [comment]
Excelente @fnnrodrigo! 

Acho que sua proposta é muito boa!

Para começar, na prática, é só acontecer um dos 4 gatilhos então, certo?

**Comment by fnnrodrigo** [comment]
Isso, @TiagoGouvea!

Segue o que pode ser nosso primeiro Changelog, sobre o site.

**Novo site do GDGJF, quer aprender algo novo?  - GDGJF Changelog v0.1**

Fala, dev! Esse é nosso primeiro "Changelog". Isso mesmo, agora o GDGJF irá te manter informado de tudo que está acontecendo em nossa comunidade. Será mais fácil para você participar, aprender coisas novas e ficar sempre por dentro das tendências do mercado.

Estreamos a versão 0.1 te convidando para uma oportunidade:

- Que tal aprender Next e Typescript? 

Pois é, estamos repaginando o nosso site (https://gdgjf.github.io/) e dessa vez isso será um projeto de toda a comunidade, liderado pelos nossos Organizers Lesley e Washington.

Está interessado em aprender uma nova tecnologia, na prática e, gratuitamente? Se inscreva nesse formulário __LINK__ que entraremos em contato para mais detalhes!

Muitas mudanças estão acontecendo no GDGJF. Fique atento aos próximos Changelogs!
#GDGJF



___________

A ideia do Link é que as pessoas se inscrevam para um papo no Zoom onde tudo será explicado e depois coordenado para o desenvolvimento do site. Pode ser feito de alguma forma diferente. @lesleyandrez e @junior201110 fiquem à vontade para adaptarem o texto ao que vocês decidiram.

@TiagoGouvea, não tenho acesso ao Mailchimp, então, assim que eles baterem o martelo, dispara pra gente =)

**Comment by TiagoGouvea** [comment]
Ótimo! Bom demais!

**Comment by lesleyandrez** [comment]
Em vez de ter esse Link para o formulário, talvez seja mais interessante para esse momento criamos um evento do GDG, no meetup ou na nova plataforma.
E o tema do evento seria apresentar o que estamos planejando para o site, compartilhar essa experiência inicial que tivemos e no evento incentivar as pessoas participarem através do github e claro contando com nossa ajuda para o que for necessário.

Para isso é preciso montar o título, descrição e imagem para o evento e marcar uma data e hora, que eu posso fazer, caso concordem com esse meu pensamento. O que acham?

**Comment by TiagoGouvea** [comment]
Acho uma boa também! Assim fica tudo público e participa quem quer.

**Comment by Francila** [comment]
Ficou muito bom @fnnrodrigo! Gostei da proposta @lesleyandrez!

**Comment by TiagoGouvea** [comment]
Enviamos já dois changelogs! O primeiro, e um fix do primeiro! Então vou considerar este projeto "realizado", mesmo sendo uma ação constante, ok? Vou fechar a issue.

Obrigado a todos por isso!
