### ISSUE TITLE
Ferramentas para manter um padrão no código

### ISSUE THREAD

**Issue by lesleyandrez** [gdgjf/gdgjf.github.io#39]
Durante o desenvolvimento inicial, senti falta de ferramentas para manter um padrão no código.
Poderíamos adicionar pelo menos o `eslint` e o `editorconfig` ao projeto.
Isso irá ajudar muito a manter a consistência quando outras pessoas forem contribuir.

**Comment by TiagoGouvea** [comment]
Acho válido. Já é uma tarefa?

**Comment by lesleyandrez** [comment]
Sim. Já é uma tarefa.

**Comment by macanhajc** [comment]
@lesleyandrez Dei uma consultada a respeito desse `editorconfig` e acredito que por ser necessário ter uma extensão instalada ele seria mais um passo opcional pra configuração correto ?

**Comment by lesleyandrez** [comment]
> @lesleyandrez Dei uma consultada a respeito desse `editorconfig` e acredito que por ser necessário ter uma extensão instalada ele seria mais um passo opcional pra configuração correto ?

Primeiro, obrigado pela contribuição.

Mesmo sendo necessário uma extensão para o `editorconfig` funcionar em alguns editores, essa ferramenta ainda pode ajudar a manter um padrão mais bem estabelecido no projeto em conjunto com as outras ferramentas que já foram configuradas.

No caso só seria importante especificar isso no `README.md`, já que isso seria um requisito, inclusive seria interessante recomendar a instalação de outras extensões como o `eslint` para ter feedback dentro do próprio editor.
